// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class DotFlipEventManager
{
        public const string achievement_clear_tutorial = "CgkI99rEtL0aEAIQAQ"; // <GPGSID>
        public const string achievement_one_coin_mode = "CgkI99rEtL0aEAIQBA"; // <GPGSID>
        public const string achievement_40_stage_clear = "CgkI99rEtL0aEAIQAg"; // <GPGSID>
        public const string achievement_80_stage_clear = "CgkI99rEtL0aEAIQAw"; // <GPGSID>
        public const string achievement_40_stage_played_in_one_coinmode = "CgkI99rEtL0aEAIQBQ"; // <GPGSID>

}

